const express = require('express');
const router = express.Router();
var nodemailer = require('nodemailer');
const controllers = require('../controllers/user')
const emailsend= require('../controllers/Mail')
const controllPay = require('../controllers/payment')
// 
const stripe = require("stripe")('sk_test_51In3w0C9IwRVISKzHG8rffN85lCiqMwZt5vOb0yCFSXH02lRAM4mTRKlfvOcrABMw28lksTswGdiXHTWcoVVltWI00xjUPV8iH',  {
  apiVersion: '2020-08-27',
})



const mailGun = require('nodemailer-mailgun-transport');

router.get('/', function(req, res){ 
  res.render('Cards', { 
  key: Publishable_Key 
  }) 
}) 
router.post('/user/create', controllers.createUser);
router.get('/users', controllers.getUsers);
router.post('/login', controllers.findUser);
router.get('/Profile/:email', controllers.getprof)
router.put('/Profile/:id',controllers.updateprof);
router.post('/payment', async (req, res, next) => {
    
  const { email,product , authToken } = req.body;
  const { token } = authToken;
  const { card } = token;

  console.log(card);


  stripe.charges.retrieve('ch_1Io55LC9IwRVISKz2wxmN9dq', {
    expand: ['customer', 'invoice.subscription'],
  });
  console.log("payment initiate ")


  const userProduct = product

  // unique ID generated by client
   const idempotencyKey = uuidv4()

   try {
       const customer = await stripe.customers.create({
           email: email,
           source: token.id
       })

       console.log('Customer Created.....')
       console.log(customer)
       
       const response = await stripe.charges.create({
           amount: userProduct.amount * 100,
           currency: 'TND',
           customer: customer.id,
           receipt_email: email,
           description: userProduct.description,
           shipping: {
               name: card.name,
               address: {
                   line1: "Tunis",
                   country: card.address_country,
                }
           }
   
       },{ idempotencyKey: idempotencyKey})

       console.log("charge response")
       console.log(response)
         
       
    
       res.json(response)
       
   } catch (err) {
       console.log("error ",err)
      res.json(err)
   }

})

router.post("/updateCardDetails/card_1IoFbPC9IwRVISKzBaFXFs4q", async (req, res) => {
  const { cardName, cardExpMonth, cardExpYear, cardId } = req.body;

  if (!cardId) {
    return res.status(400).send({
      Error: "CardID is Required to update",
    });
  }
  try {
    const card = await stripe.customers.updateSource(customerId, cardId, {
      name: cardName,
      exp_month: cardExpMonth,
      exp_year: cardExpYear,
    });
    return res.status(200).send({
      updatedCard: card,
    });
  } catch (error) {
    return res.status(400).send(error);
  }
});

       

process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 1;
router.post('/sendemail',(req,res,next)=>{
    console.log(req.body)
    
    let data =req.body
    
    const auth = {
        
        auth: {
          api_key: "f0a9606f1bdd1f1ac7dd17a7024f8ec3-4b1aa784-b790fe6f",
          domain: "sandbox3ea2588c717344008700cdb3315efdcc.mailgun.org"
        }}
  
    var transporter = nodemailer.createTransport(mailGun(auth));

   
    var mailOptions = {
    from: data.email,
    to: 'dhia11aouichaoui@gmail.com',
    subject: `Contact name: ${data.name}, ${data.subject} `,
    text: `${data.message}`
    };
  
    transporter.sendMail(mailOptions, function(error, info){
    if (error) {
    console.log(error);
    res.send('error') 
    }
    else {
    console.log('Email sent: ' + info.response);
    res.send('Sent Successfully')
    }
    });
    })
// process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0;
// let transporter = nodemailer.createTransport({
//     host:" smtp.mailgun.org",
//     port:587,
//     auth:{
//      user:"postmaster@sandbox678d878f7e784890a6bfab346b57530f.mailgun.org",
//      pass: "9f064d8e2691f6dcec6f182931ed854d-4b1aa784-276c2e15"
// }
// });
//   transporter.verify(function(error, success) {
//     if (error) {
//       console.log(error);
//     } else {
//       console.log("Server is ready to take our messages");
//     }
//   });
//   router.post('/send', (req, res, next) => {
//     var transporter=nodemailer.createTransport({
//         service:'gmail',
//         auth: {
//           user: "dhia12aouichaoui@gmail.com", //replace with the email address
//           pass: "27211712rr" //replace with the password
//         }
//       });
//     var name = req.body.name
//     var email = req.body.email
//     var subject = req.body.subject
//     var message = req.body.message
//     var content = `name: ${name} \n email: ${email} \n subject: ${subject} \n message: ${message} `
//     var mail = {
//       from: name,
//       to: "dhia12aouichaoui@gmail.com",
//       subject: subject,
//       text: content
//     }
//     transporter.sendMail(mail, (err, data) => {
//       if (err) {
//         res.json({
//           status: 'fail'
//         })
//       } else {
//         res.json({
//          status: 'success'
//         })
//       }
//     })
//   })
module.exports = router;
