
// import express, { Request, Response, NextFunction } from 'express'
// import cors from 'cors'
// import bodyParser from 'body-parser'
// import { Stripe } from 'stripe'
// import {v4 as uuidv4} from 'uuid'
 
// const stripe = new Stripe('sk_test_51In3w0C9IwRVISKzHG8rffN85lCiqMwZt5vOb0yCFSXH02lRAM4mTRKlfvOcrABMw28lksTswGdiXHTWcoVVltWI00xjUPV8iH',  {
//     apiVersion: '2020-08-27',
//   })
 
//  const app = express()
//  app.use(cors())
//  app.use(bodyParser.json())
  
// // interface Product {
// //     description: string,
// //     amount: number
// // }

// app.post('/payment', async (req, res, next) => {
    
//     const { email,product , authToken } = req.body;
//     const { token } = authToken;
//     const { card } = token;

//     console.log(card);


  
//     console.log("payment initiate ")

 
//     const userProduct = product

//     // unique ID generated by client
//      const idempotencyKey = uuidv4()

//      try {
//          const customer = await stripe.customers.create({
//              email: email,
//              source: token.id
//          })

//          console.log('Customer Created.....')
//          console.log(customer)
         
//          const response = await stripe.charges.create({
//              amount: userProduct.amount * 100,
//              currency: 'TND',
//              customer: customer.id,
//              receipt_email: email,
//              description: userProduct.description,
//              shipping: {
//                  name: card.name,
//                  address: {
//                      line1: "Tunis",
//                      country: card.address_country,
//                   }
//              }
     
//          },{ idempotencyKey: idempotencyKey})

//          console.log("charge response")
//          console.log(response)
           
         
      
//          res.json(response)
         
//      } catch (err) {
//          console.log("error ",err)
//         res.json(err)
//      }
  
// })